<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php $this->out($meta_title, false); ?></title>
    <meta name="robots" content="<?php $this->out($meta_index); ?>" />
    <meta name="description" content="<?php $this->out($meta_description, false); ?>">
    <link rel="alternate" type="application/rss+xml" href="/blog/feed">
    <link rel="stylesheet" href="/css/blog.css?v=2019021701">
</head>
<body>
<nav class="topnav">
    <ul>
        <li class="first"><a href="/">Bloatless Blog</a></li>
        <li><a href="/about">About</a></li>
        <li class="last">
            <a href="/blog/feed">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M4 11a9 9 0 0 1 9 9"></path>
                    <path d="M4 4a16 16 0 0 1 16 16"></path>
                    <circle cx="5" cy="19" r="1"></circle>
                </svg>
            </a>
        </li>
    </ul>
</nav>

<div class="content">
    <?php $this->out($content, false); ?>
</div>

</body>
</html>
